using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using TSQL.Tokens;

namespace TSQL.Color
{
	public class SQLColorizer
	{
		#region KnownFunctions

		private static Dictionary<string, string> KnownFunctions = new Dictionary<string, string>
		{
			{"AVG", null},
			{"CHECKSUM_AGG", null},
			{"COUNT", null},
			{"COUNT_BIG", null},
			{"GROUPING", null},
			{"GROUPING_ID", null},
			{"MAX", null},
			{"MIN", null},
			{"SUM", null},
			{"STDEV", null},
			{"STDEVP", null},
			{"VAR", null},
			{"VARP", null},
			{"SYSDATETIME", null},
			{"SYSDATETIMEOFFSET", null},
			{"SYSUTCDATETIME", null},
			{"CURRENT_TIME", null},
			{"CURRENT_TIMESTAMP", null},
			{"GETDATE", null},
			{"GETUTCDATE", null},
			{"DATENAME", null},
			{"DATEPART", null},
			{"DAY", null},
			{"MONTH", null},
			{"YEAR", null},
			{"DATEFROMPARTS", null},
			{"DATETIME2FROMPARTS", null},
			{"DATETIMEFROMPARTS", null},
			{"DATETIMEOFFSETFROMPARTS", null},
			{"SMALLDATETIMEFROMPARTS", null},
			{"TIMEFROMPARTS", null},
			{"DATEDIFF", null},
			{"DATEADD", null},
			{"EOMONTH", null},
			{"SWITCHOFFSET", null},
			{"TODATETIMEOFFSET", null},
			{"ISDATE", null},
			{"CHOOSE", null},
			{"IIF", null},
			{"ABS", null},
			{"ACOS", null},
			{"ASIN", null},
			{"ATAN", null},
			{"ATN2", null},
			{"CEILING", null},
			{"COS", null},
			{"COT", null},
			{"DEGREES", null},
			{"EXP", null},
			{"FLOOR", null},
			{"LOG", null},
			{"LOG10", null},
			{"PI", null},
			{"POWER", null},
			{"RADIANS", null},
			{"RAND", null},
			{"ROUND", null},
			{"SIGN", null},
			{"SIN", null},
			{"SQRT", null},
			{"SQUARE", null},
			{"TAN", null},
			{"RANK", null},
			{"DENSE_RANK", null},
			{"NTILE", null},
			{"ROW_NUMBER", null},
			{"ASCII", null},
			{"CHARINDEX", null},
			{"CONCAT", null},
			{"DIFFERENCE", null},
			{"FORMAT", null},
			{"LEN", null},
			{"LOWER", null},
			{"LTRIM", null},
			{"PATINDEX", null},
			{"QUOTENAME", null},
			{"REPLACE", null},
			{"REPLICATE", null},
			{"REVERSE", null},
			{"RTRIM", null},
			{"SOUNDEX", null},
			{"SPACE", null},
			{"STR", null},
			{"STRING_AGG", null},
			{"STRING_ESCAPE", null},
			{"STRING_SPLIT", null},
			{"STUFF", null},
			{"SUBSTRING", null},
			{"TRIM", null},
			{"UNICODE", null},
			{"UPPER", null},
			{"GETANSINULL", null},
			{"HOST_ID", null},
			{"HOST_NAME", null},
			{"ISNULL", null},
			{"ISNUMERIC", null},
			{"MIN_ACTIVE_ROWVERSION", null},
			{"NEWID", null},
			{"NEWSEQUENTIALID", null},
			{"ROWCOUNT_BIG", null},
			{"SESSION_CONTEXT", null},
			{"SESSION_ID", null},
			{"XACT_STATE", null},
			{"FILEPROPERTY", null},
			{"FULLTEXTCATALOGPROPERTY", null},
			{"FULLTEXTSERVICEPROPERTY", null},
			{"INDEX_COL", null},
			{"INDEXKEY_PROPERTY", null},
			{"INDEXPROPERTY", null},
			{"OBJECT_DEFINITION", null},
			{"OBJECT_ID", null},
			{"OBJECT_NAME", null},
			{"OBJECT_SCHEMA_NAME", null},
			{"OBJECTPROPERTY", null},
			{"OBJECTPROPERTYEX", null},
			{"ORIGINAL_DB_NAME", null},
			{"PARSENAME", null},
			{"SCHEMA_ID", null},
			{"SCHEMA_NAME", null},
			{"SCOPE_IDENTITY", null},
			{"SERVERPROPERTY", null},
			{"STATS_DATE", null},
			{"TYPE_ID", null},
			{"TYPE_NAME", null},
			{"TYPEPROPERTY", null},
			{"APP_NAME", null},
			{"APPLOCK_MODE", null},
			{"APPLOCK_TEST", null},
			{"ASSEMBLYPROPERTY", null},
			{"COL_LENGTH", null},
			{"COL_NAME", null},
			{"COLUMNPROPERTY", null},
			{"DATABASE_PRINCIPAL_ID", null},
			{"DATABASEPROPERTYEX", null},
			{"DB_ID", null},
			{"DB_NAME", null},
			{"FILE_ID", null},
			{"FILE_IDEX", null},
			{"FILE_NAME", null},
			{"FILEGROUP_ID", null},
			{"FILEGROUP_NAME", null},
			{"FILEGROUPPROPERTY", null},
			{"TEXTPTR", null},
			{"TEXTVALID", null},
			{"BINARY_CHECKSUM", null},
			{"CHECKSUM", null},
			{"COMPRESS", null},
			{"CONNECTIONPROPERTY", null},
			{"CONTEXT_INFO", null},
			{"CURRENT_REQUEST_ID", null},
			{"CURRENT_TRANSACTION_ID", null},
			{"DECOMPRESS", null},
			{"ERROR_LINE", null},
			{"ERROR_MESSAGE", null},
			{"ERROR_NUMBER", null},
			{"ERROR_PROCEDURE", null},
			{"ERROR_SEVERITY", null},
			{"ERROR_STATE", null},
			{"FORMATMESSAGE", null},
			{"GET_FILESTREAM_TRANSACTION_CONTEXT", null}
		};

		#endregion

		#region PseudoKeywords

		private static Dictionary<string, string> PseudoKeywords = new Dictionary<string, string>
			{
				{"ABORT", null},
				{"ABORT_AFTER_WAIT", null},
				{"ABSENT", null},
				{"ABSOLUTE", null},
				{"ACCENT_SENSITIVITY", null},
				{"ACCEPTABLE_CURSOPT", null},
				{"ACP", null},
				{"ACTION", null},
				{"ACTIVATION", null},
				{"ADDRESS", null},
				{"ADMIN", null},
				{"AES_128", null},
				{"AES_192", null},
				{"AES_256", null},
				{"AFFINITY", null},
				{"AFTER", null},
				{"AGGREGATE", null},
				{"ALGORITHM", null},
				{"ALL_CONSTRAINTS", null},
				{"ALL_ERRORMSGS", null},
				{"ALL_INDEXES", null},
				{"ALL_LEVELS", null},
				{"ALL_RESULTS", null},
				{"ALLOW_CONNECTIONS", null},
				{"ALLOW_DUP_ROW", null},
				{"ALLOW_ENCRYPTED_VALUE_MODIFICATIONS", null},
				{"ALLOW_PAGE_LOCKS", null},
				{"ALLOW_ROW_LOCKS", null},
				{"ALLOW_SNAPSHOT_ISOLATION", null},
				{"ALTERCOLUMN", null},
				{"ALWAYS", null},
				{"ANONYMOUS", null},
				{"ANSI_DEFAULTS", null},
				{"ANSI_NULL_DEFAULT", null},
				{"ANSI_NULL_DFLT_OFF", null},
				{"ANSI_NULL_DFLT_ON", null},
				{"ANSI_NULLS", null},
				{"ANSI_PADDING", null},
				{"ANSI_WARNINGS", null},
				{"APPDOMAIN", null},
				{"APPEND", null},
				{"APPLICATION", null},
				{"ARITHABORT", null},
				{"ARITHIGNORE", null},
				{"ASSEMBLY", null},
				{"ASYMMETRIC", null},
				{"ASYNCHRONOUS_COMMIT", null},
				{"AT", null},
				{"ATAN2", null},
				{"ATOMIC", null},
				{"ATTACH", null},
				{"ATTACH_FORCE_REBUILD_LOG", null},
				{"ATTACH_REBUILD_LOG", null},
				{"AUDIT", null},
				{"AUTH_REALM", null},
				{"AUTHENTICATION", null},
				{"AUTO", null},
				{"AUTO_CLEANUP", null},
				{"AUTO_CLOSE", null},
				{"AUTO_CREATE_STATISTICS", null},
				{"AUTO_SHRINK", null},
				{"AUTO_UPDATE_STATISTICS", null},
				{"AUTO_UPDATE_STATISTICS_ASYNC", null},
				{"AUTOMATED_BACKUP_PREFERENCE ", null},
				{"AUTOMATIC", null},
				{"AUTOPILOT", null},
				{"AVAILABILITY", null},
				{"AVAILABILITY_MODE", null},
				{"BACKUP_PRIORITY", null},
				{"BASE64", null},
				{"BASIC", null},
				{"BATCHES", null},
				{"BATCHSIZE", null},
				{"BEFORE", null},
				{"BIGINT", null},
				{"BINARY", null},
				{"BINDING", null},
				{"BIT", null},
				{"BLOCK", null},
				{"BLOCKSIZE", null},
				{"BMK", null},
				{"BROKER", null},
				{"BROKER_INSTANCE", null},
				{"BUCKET_COUNT", null},
				{"BUFFER", null},
				{"BUFFERCOUNT", null},
				{"BULK_LOGGED", null},
				{"CALL", null},
				{"CALLER", null},
				{"CARD", null},
				{"CATALOG", null},
				{"CATCH", null},
				{"CERT", null},
				{"CERTIFICATE", null},
				{"CHANGE_RETENTION", null},
				{"CHANGE_TRACKING", null},
				{"CHANGE_TRACKING_CONTEXT", null},
				{"CHANGES", null},
				{"CHAR", null},
				{"CHARACTER", null},
				{"CHARACTER_SET", null},
				{"CHECK_EXPIRATION", null},
				{"CHECK_POLICY", null},
				{"CHECKCONSTRAINTS", null},
				{"CHECKINDEX", null},
				{"CLEANUP_POLICY", null},
				{"CLEAR", null},
				{"CLEAR_PORT", null},
				{"CODEPAGE", null},
				{"COLLECTION", null},
				{"COLUMN_ENCRYPTION_KEY", null},
				{"COLUMN_MASTER_KEY", null},
				{"COLUMNSTORE", null},
				{"COLUMNSTORE_ARCHIVE", null},
				{"COLV_80_TO_100", null},
				{"COLV_100_TO_80", null},
				{"COMMIT_DIFFERENTIAL_BASE", null},
				{"COMMITTED", null},
				{"COMPATIBILITY_LEVEL", null},
				{"COMPRESS_ALL_ROW_GROUPS", null},
				{"COMPRESSION", null},
				{"COMPRESSION_DELAY", null},
				{"CONCAT_NULL_YIELDS_NULL", null},
				{"CONCATENATE", null},
				{"CONFIGURATION", null},
				{"CONNECT", null},
				{"CONTINUE_AFTER_ERROR", null},
				{"CONTRACT", null},
				{"CONTRACT_NAME", null},
				{"CONTROL", null},
				{"CONVERSATION", null},
				{"CONVERSATION_GROUP_ID", null},
				{"CONVERSATION_HANDLE", null},
				{"COPY", null},
				{"COPY_ONLY", null},
				{"COUNT_ROWS", null},
				{"COUNTER", null},
				{"CREDENTIAL", null},
				{"CRYPTOGRAPHIC", null},
				{"CRYPTOGRAPHIC_PROVIDER", null},
				{"CUBE", null},
				{"CURSOR_CLOSE_ON_COMMIT", null},
				{"CURSOR_DEFAULT", null},
				{"DATA", null},
				{"DATA_COMPRESSION", null},
				{"DATA_FLUSH_INTERVAL_SECONDS", null},
				{"DATA_MIRRORING", null},
				{"DATA_PURITY", null},
				{"DATA_SOURCE", null},
				{"DATABASE_NAME", null},
				{"DATABASE_SNAPSHOT", null},
				{"DATAFILETYPE", null},
				{"DATE_CORRELATION_OPTIMIZATION", null},
				{"DATE", null},
				{"DATEFIRST", null},
				{"DATEFORMAT", null},
				{"DATE_FORMAT", null},
				{"DATETIME", null},
				{"DATETIME2", null},
				{"DATETIMEOFFSET", null},
				{"DAYS", null},
				{"DB_CHAINING", null},
				{"DBID", null},
				{"DBIDEXEC", null},
				{"DBO_ONLY", null},
				{"DEADLOCK_PRIORITY", null},
				{"DEC", null},
				{"DECIMAL", null},
				{"DECRYPT", null},
				{"DECRYPT_A", null},
				{"DECRYPTION", null},
				{"DEFAULT_DATABASE", null},
				{"DEFAULT_LANGUAGE", null},
				{"DEFAULT_LOGON_DOMAIN", null},
				{"DEFAULT_SCHEMA", null},
				{"DEFINITION", null},
				{"DELAY", null},
				{"DELAYED_DURABILITY", null},
				{"DELIMITEDTEXT", null},
				{"DENSITY_VECTOR", null},
				{"DEPENDENT", null},
				{"DES", null},
				{"DESCRIPTION", null},
				{"DESIRED_STATE", null},
				{"DESX", null},
				{"DIFFERENTIAL", null},
				{"DIGEST", null},
				{"DISABLE", null},
				{"DISABLE_BROKER", null},
				{"DISABLE_DEF_CNST_CHK", null},
				{"DISABLED", null},
				{"DISK", null},
				{"DISTRIBUTION", null},
				{"DROP_EXISTING", null},
				{"DTS_BUFFERS", null},
				{"DUMP", null},
				{"DURABILITY", null},
				{"DYNAMIC", null},
				{"ELEMENTS", null},
				{"EMERGENCY", null},
				{"EMPTY", null},
				{"ENABLE", null},
				{"ENABLE_BROKER", null},
				{"ENABLED", null},
				{"ENCODING", null},
				{"ENCRYPTED", null},
				{"ENCRYPTED_VALUE", null},
				{"ENCRYPTION", null},
				{"ENCRYPTION_TYPE", null},
				{"ENDPOINT", null},
				{"ENDPOINT_URL", null},
				{"ENHANCEDINTEGRITY", null},
				{"ENTRY", null},
				{"ERROR_BROKER_CONVERSATIONS", null},
				{"ERRORFILE", null},
				{"ESTIMATEONLY", null},
				{"EVENT", null},
				{"EXECUTABLE", null},
				{"EXPAND", null},
				{"EXPIREDATE", null},
				{"EXPIRY_DATE", null},
				{"EXPLICIT", null},
				{"EXTERNAL_ACCESS", null},
				{"FAILOVER", null},
				{"FAILOVER_MODE", null},
				{"FAILURE_CONDITION_LEVEL", null},
				{"FAST", null},
				{"FAST_FORWARD", null},
				{"FASTFIRSTROW", null},
				{"FEDERATED_SERVICE_ACCOUNT", null},
				{"FIELD_TERMINATOR", null},
				{"FIELDTERMINATOR", null},
				{"FILELISTONLY", null},
				{"FILEGROUP", null},
				{"FILENAME", null},
				{"FILESTREAM", null},
				{"FILESTREAM_LOG", null},
				{"FILESTREAM_ON", null},
				{"FILETABLE", null},
				{"FILE_FORMAT", null},
				{"FILTER", null},
				{"FIPS_FLAGGER", null},
				{"FIRE_TRIGGERS", null},
				{"FIRST", null},
				{"FIRSTROW", null},
				{"FLOAT", null},
				{"FLUSH_INTERVAL_SECONDS", null},
				{"FMTONLY", null},
				{"FOLLOWING", null},
				{"FORCE", null},
				{"FORCE_FAILOVER_ALLOW_DATA_LOSS", null},
				{"FORCE_SERVICE_ALLOW_DATA_LOSS", null},
				{"FORCED", null},
				{"FORCEPLAN", null},
				{"FORMATFILE", null},
				{"FORMAT_OPTIONS", null},
				{"FORMAT_TYPE", null},
				{"FORMSOF", null},
				{"FORWARD_ONLY", null},
				{"FREE_CURSORS", null},
				{"FREE_EXEC_CONTEXT", null},
				{"FULLSCAN", null},
				{"FULLTEXT", null},
				{"FULLTEXTALL", null},
				{"FULLTEXTKEY", null},
				{"GENERATED", null},
				{"GET", null},
				{"GEOGRAPHY", null},
				{"GEOMETRY", null},
				{"GLOBAL", null},
				{"GOVERNOR", null},
				{"GUID", null},
				{"HADOOP", null},
				{"HARDENING", null},
				{"HASH", null},
				{"HASHED", null},
				{"HEADER_LIMIT", null},
				{"HEADERONLY", null},
				{"HEALTH_CHECK_TIMEOUT", null},
				{"HIDDEN", null},
				{"HIERARCHYID", null},
				{"HISTOGRAM", null},
				{"HISTOGRAM_STEPS", null},
				{"HITS_CURSORS", null},
				{"HITS_EXEC_CONTEXT", null},
				{"HOURS", null},
				{"HTTP", null},
				{"IDENTITY_VALUE", null},
				{"IFNULL", null},
				{"IGNORE_CONSTRAINTS", null},
				{"IGNORE_DUP_KEY", null},
				{"IGNORE_DUP_ROW", null},
				{"IGNORE_TRIGGERS", null},
				{"IMAGE", null},
				{"IMMEDIATE", null},
				{"IMPLICIT_TRANSACTIONS", null},
				{"INCLUDE", null},
				{"INCLUDE_NULL_VALUES", null},
				{"INFLECTIONAL", null},
				{"INIT", null},
				{"INITIATOR", null},
				{"INSENSITIVE", null},
				{"INSTEAD", null},
				{"INT", null},
				{"INTEGER", null},
				{"INTEGRATED", null},
				{"INTERMEDIATE", null},
				{"INTERVAL_LENGTH_MINUTES", null},
				{"INUSE_CURSORS", null},
				{"INUSE_EXEC_CONTEXT", null},
				{"IO", null},
				{"ISABOUT", null},
				{"ISO_WEEK", null},
				{"ISOLATION", null},
				{"JOB_TRACKER_LOCATION", null},
				{"JSON", null},
				{"KEEP", null},
				{"KEEP_NULLS", null},
				{"KEEP_REPLICATION", null},
				{"KEEPDEFAULTS", null},
				{"KEEPFIXED", null},
				{"KEEPIDENTITY", null},
				{"KEEPNULLS", null},
				{"KERBEROS", null},
				{"KEY_PATH", null},
				{"KEY_SOURCE", null},
				{"KEY_STORE_PROVIDER_NAME", null},
				{"KEYSET", null},
				{"KILOBYTES_PER_BATCH", null},
				{"LABELONLY", null},
				{"LANGID", null},
				{"LANGUAGE", null},
				{"LAST", null},
				{"LASTROW", null},
				{"LEGACY_CARDINALITY_ESTIMATION", null},
				{"LENGTH", null},
				{"LEVEL", null},
				{"LIFETIME", null},
				{"LINEAGE_80_TO_100", null},
				{"LINEAGE_100_TO_80", null},
				{"LISTENER_IP", null},
				{"LISTENER_PORT", null},
				{"LOAD", null},
				{"LOADHISTORY", null},
				{"LOB_COMPACTION", null},
				{"LOCAL", null},
				{"LOCAL_SERVICE_NAME", null},
				{"LOCATE", null},
				{"LOCATION", null},
				{"LOCK_ESCALATION", null},
				{"LOCK_TIMEOUT", null},
				{"LOCKRES", null},
				{"LOGIN", null},
				{"LOGIN_TYPE", null},
				{"LOOP", null},
				{"MANUAL", null},
				{"MARK_IN_USE_FOR_REMOVAL", null},
				{"MASKED", null},
				{"MASTER", null},
				{"MAX_QUEUE_READERS", null},
				{"MAX_DURATION", null},
				{"MAX_OUTSTANDING_IO_PER_VOLUME", null},
				{"MAXDOP", null},
				{"MAXERRORS", null},
				{"MAXLENGTH", null},
				{"MAXTRANSFERSIZE", null},
				{"MAX_PLANS_PER_QUERY", null},
				{"MAX_STORAGE_SIZE_MB", null},
				{"MEDIADESCRIPTION", null},
				{"MEDIANAME", null},
				{"MEDIAPASSWORD", null},
				{"MEMOGROUP", null},
				{"MEMORY_OPTIMIZED", null},
				{"MESSAGE", null},
				{"MESSAGE_FORWARD_SIZE", null},
				{"MESSAGE_FORWARDING", null},
				{"MICROSECOND", null},
				{"MILLISECOND", null},
				{"MINUTES", null},
				{"MIRROR_ADDRESS", null},
				{"MISSES_CURSORS", null},
				{"MISSES_EXEC_CONTEXT", null},
				{"MIXED", null},
				{"MODIFY", null},
				{"MONEY", null},
				{"MOVE", null},
				{"MULTI_USER", null},
				{"MUST_CHANGE", null},
				{"NAME", null},
				{"NAMESPACE", null},
				{"NANOSECOND", null},
				{"NATIVE", null},
				{"NATIVE_COMPILATION", null},
				{"NCHAR", null},
				{"NCHARACTER", null},
				{"NEVER", null},
				{"NEW_ACCOUNT", null},
				{"NEW_BROKER", null},
				{"NEWNAME", null},
				{"NEXT", null},
				{"NO", null},
				{"NO_BROWSETABLE", null},
				{"NO_CHECKSUM", null},
				{"NO_COMPRESSION", null},
				{"NO_INFOMSGS", null},
				{"NO_TRIGGERS", null},
				{"NO_TRUNCATE", null},
				{"NOCOUNT", null},
				{"NOEXEC", null},
				{"NOEXPAND", null},
				{"NOFORMAT", null},
				{"NOINIT", null},
				{"NOLOCK", null},
				{"NONATOMIC", null},
				{"NONDURABLE", null},
				{"NONE", null},
				{"NORECOMPUTE", null},
				{"NORECOVERY", null},
				{"NORESET", null},
				{"NOREWIND", null},
				{"NOSKIP", null},
				{"NOTIFICATION", null},
				{"NOUNLOAD", null},
				{"NOW", null},
				{"NOWAIT", null},
				{"NTEXT", null},
				{"NTLM", null},
				{"NUMERIC", null},
				{"NUMERIC_ROUNDABORT", null},
				{"NVARCHAR", null},
				{"OBJECT", null},
				{"OBJID", null},
				{"OEM", null},
				{"OFFLINE", null},
				{"OLD_ACCOUNT", null},
				{"ONLINE", null},
				{"OPERATION_MODE", null},
				{"OPENJSON", null},
				{"OPTIMISTIC", null},
				{"ORC", null},
				{"OUT", null},
				{"OUTPUT", null},
				{"OVERRIDE", null},
				{"OWNER", null},
				{"OWNERSHIP", null},
				{"PAD_INDEX", null},
				{"PAGE", null},
				{"PAGE_CHECKSUM", null},
				{"PAGE_VERIFY", null},
				{"PAGECOUNT", null},
				{"PAGLOCK", null},
				{"PARAM", null},
				{"PARAMETER_SNIFFING", null},
				{"PARAMETER_TYPE_EXPANSION", null},
				{"PARAMETERIZATION", null},
				{"PARQUET", null},
				{"PARSEONLY", null},
				{"PARTIAL", null},
				{"PARTITION", null},
				{"PARTNER", null},
				{"PASSWORD", null},
				{"PATH", null},
				{"PAUSE", null},
				{"PERCENTAGE", null},
				{"PERMISSION_SET", null},
				{"PERSISTED", null},
				{"PERIOD", null},
				{"PHYSICAL_ONLY", null},
				{"PLAN_FORCING_MODE", null},
				{"POLICY", null},
				{"POOL", null},
				{"POPULATION", null},
				{"PORTS", null},
				{"PRECEDING", null},
				{"PRECISION", null},
				{"PREDICATE", null},
				{"PRESUME_ABORT", null},
				{"PRIMARY_ROLE", null},
				{"PRIOR", null},
				{"PRIORITY ", null},
				{"PRIORITY_LEVEL", null},
				{"PRIVATE", null},
				{"PROCEDURE_NAME", null},
				{"PROFILE", null},
				{"PROVIDER", null},
				{"QUERY_CAPTURE_MODE", null},
				{"QUERY_GOVERNOR_COST_LIMIT", null},
				{"QUERY_OPTIMIZER_HOTFIXES", null},
				{"QUERY_STORE", null},
				{"QUEUE", null},
				{"QUOTED_IDENTIFIER", null},
				{"RANGE", null},
				{"RAW", null},
				{"RCFILE", null},
				{"RC2", null},
				{"RC4", null},
				{"RC4_128", null},
				{"RDBMS", null},
				{"READ_COMMITTED_SNAPSHOT", null},
				{"READ_ONLY", null},
				{"READ_WRITE", null},
				{"READCOMMITTED", null},
				{"READCOMMITTEDLOCK", null},
				{"READONLY", null},
				{"READPAST", null},
				{"READUNCOMMITTED", null},
				{"READWRITE", null},
				{"REAL", null},
				{"REBUILD", null},
				{"RECEIVE", null},
				{"RECMODEL_70BACKCOMP", null},
				{"RECOMPILE", null},
				{"RECOVERY", null},
				{"RECURSIVE", null},
				{"RECURSIVE_TRIGGERS", null},
				{"REDO_QUEUE", null},
				{"REJECT_SAMPLE_VALUE", null},
				{"REJECT_TYPE", null},
				{"REJECT_VALUE", null},
				{"RELATIVE", null},
				{"REMOTE", null},
				{"REMOTE_DATA_ARCHIVE", null},
				{"REMOTE_PROC_TRANSACTIONS", null},
				{"REMOTE_SERVICE_NAME", null},
				{"REMOVE", null},
				{"REMOVED_CURSORS", null},
				{"REMOVED_EXEC_CONTEXT", null},
				{"REORGANIZE", null},
				{"REPEAT", null},
				{"REPEATABLE", null},
				{"REPEATABLEREAD", null},
				{"REPLICA", null},
				{"REPLICATED", null},
				{"REPLNICK_100_TO_80", null},
				{"REPLNICKARRAY_80_TO_100", null},
				{"REPLNICKARRAY_100_TO_80", null},
				{"REQUIRED", null},
				{"REQUIRED_CURSOPT", null},
				{"RESAMPLE", null},
				{"RESET", null},
				{"RESOURCE", null},
				{"RESOURCE_MANAGER_LOCATION", null},
				{"RESTART", null},
				{"RESTRICTED_USER", null},
				{"RESUME", null},
				{"RETAINDAYS", null},
				{"RETENTION", null},
				{"REWIND", null},
				{"REWINDONLY", null},
				{"RETURNS", null},
				{"ROBUST", null},
				{"ROLE", null},
				{"ROLLUP", null},
				{"ROOT", null},
				{"ROUND_ROBIN", null},
				{"ROUTE", null},
				{"ROW", null},
				{"ROWDUMP", null},
				{"ROWLOCK", null},
				{"ROW_TERMINATOR", null},
				{"ROWS", null},
				{"ROWS_PER_BATCH", null},
				{"ROWSETS_ONLY", null},
				{"ROWTERMINATOR", null},
				{"ROWVERSION", null},
				{"RSA_1024", null},
				{"RSA_2048", null},
				{"RSA_3072", null},
				{"RSA_4096", null},
				{"RSA_512", null},
				{"SAFE", null},
				{"SAFETY", null},
				{"SAMPLE", null},
				{"SCHEMABINDING", null},
				{"SCOPED", null},
				{"SCROLL", null},
				{"SCROLL_LOCKS", null},
				{"SDDL", null},
				{"SECEXPR", null},
				{"SECONDARY", null},
				{"SECONDARY_ONLY", null},
				{"SECONDARY_ROLE", null},
				{"SECRET", null},
				{"SECURITY", null},
				{"SECURITYAUDIT", null},
				{"SELECTIVE", null},
				{"SELF", null},
				{"SEND", null},
				{"SENT", null},
				{"SEQUENCE", null},
				{"SERDE_METHOD", null},
				{"SERIALIZABLE", null},
				{"SERVER", null},
				{"SERVICE", null},
				{"SERVICE_BROKER", null},
				{"SERVICE_NAME", null},
				{"SERVICE_OBJECTIVE", null},
				{"SESSION_TIMEOUT", null},
				{"SESSION", null},
				{"SESSIONS", null},
				{"SETERROR", null},
				{"SETOPTS", null},
				{"SETS", null},
				{"SHARD_MAP_MANAGER", null},
				{"SHARD_MAP_NAME", null},
				{"SHARDED", null},
				{"SHARED_MEMORY", null},
				{"SHOW_STATISTICS", null},
				{"SHOWPLAN_ALL", null},
				{"SHOWPLAN_TEXT", null},
				{"SHOWPLAN_XML", null},
				{"SHOWPLAN_XML_WITH_RECOMPILE", null},
				{"SHRINKDB", null},
				{"SID", null},
				{"SIGNATURE", null},
				{"SIMPLE", null},
				{"SINGLE_BLOB", null},
				{"SINGLE_CLOB", null},
				{"SINGLE_NCLOB", null},
				{"SINGLE_USER", null},
				{"SINGLETON", null},
				{"SITE", null},
				{"SIZE_BASED_CLEANUP_MODE", null},
				{"SKIP", null},
				{"SMALLDATETIME", null},
				{"SMALLINT", null},
				{"SMALLMONEY", null},
				{"SNAPSHOT", null},
				{"SNAPSHOT_IMPORT", null},
				{"SNAPSHOTRESTOREPHASE", null},
				{"SOAP", null},
				{"SOFTNUMA", null},
				{"SORT_IN_TEMPDB", null},
				{"SORTED_DATA", null},
				{"SORTED_DATA_REORG", null},
				{"SPATIAL", null},
				{"SQL", null},
				{"SQL_BIGINT", null},
				{"SQL_BINARY", null},
				{"SQL_BIT", null},
				{"SQL_CHAR", null},
				{"SQL_DATE", null},
				{"SQL_DECIMAL", null},
				{"SQL_DOUBLE", null},
				{"SQL_FLOAT", null},
				{"SQL_GUID", null},
				{"SQL_HANDLE", null},
				{"SQL_LONGVARBINARY", null},
				{"SQL_LONGVARCHAR", null},
				{"SQL_NUMERIC", null},
				{"SQL_REAL", null},
				{"SQL_SMALLINT", null},
				{"SQL_TIME", null},
				{"SQL_TIMESTAMP", null},
				{"SQL_TINYINT", null},
				{"SQL_TSI_DAY", null},
				{"SQL_TSI_FRAC_SECOND", null},
				{"SQL_TSI_HOUR", null},
				{"SQL_TSI_MINUTE", null},
				{"SQL_TSI_MONTH", null},
				{"SQL_TSI_QUARTER", null},
				{"SQL_TSI_SECOND", null},
				{"SQL_TSI_WEEK", null},
				{"SQL_TSI_YEAR", null},
				{"SQL_TYPE_DATE", null},
				{"SQL_TYPE_TIME", null},
				{"SQL_TYPE_TIMESTAMP", null},
				{"SQL_VARBINARY", null},
				{"SQL_VARCHAR", null},
				{"SQL_VARIANT", null},
				{"SQL_WCHAR", null},
				{"SQL_WLONGVARCHAR", null},
				{"SSL", null},
				{"SSL_PORT", null},
				{"STANDARD", null},
				{"STANDBY", null},
				{"START", null},
				{"START_DATE", null},
				{"STARTED", null},
				{"STAT_HEADER", null},
				{"STATE", null},
				{"STATEMENT", null},
				{"STATIC", null},
				{"STATISTICS_INCREMENTAL", null},
				{"STATISTICS_NORECOMPUTE", null},
				{"STATISTICS_ONLY", null},
				{"STATMAN", null},
				{"STATS_STREAM", null},
				{"STATUS", null},
				{"STOP", null},
				{"STOP_ON_ERROR", null},
				{"STOPAT", null},
				{"STOPATMARK", null},
				{"STOPBEFOREMARK", null},
				{"STOPLIST", null},
				{"STOPPED", null},
				{"STRING_DELIMITER", null},
				{"SUBJECT", null},
				{"SUPPLEMENTAL_LOGGING", null},
				{"SUPPORTED", null},
				{"SUSPEND", null},
				{"SYMMETRIC", null},
				{"SYNCHRONOUS_COMMIT", null},
				{"SYNONYM", null},
				{"SYSNAME", null},
				{"SYSTEM", null},
				{"SYSTEM_TIME", null},
				{"SYSTEM_VERSIONING", null},
				{"TABLERESULTS", null},
				{"TABLOCK", null},
				{"TABLOCKX", null},
				{"TAKE", null},
				{"TAPE", null},
				{"TARGET", null},
				{"TARGET_INDEX", null},
				{"TARGET_PARTITION", null},
				{"TCP", null},
				{"TEMPORAL_HISTORY_RETENTION", null},
				{"TEXT", null},
				{"TEXTIMAGE_ON", null},
				{"THESAURUS", null},
				{"THROW", null},
				{"TIME", null},
				{"TIMEOUT", null},
				{"TIMESTAMP", null},
				{"TINYINT", null},
				{"TORN_PAGE_DETECTION", null},
				{"TRACK_COLUMNS_UPDATED", null},
				{"TRANSFER", null},
				{"TRIPLE_DES", null},
				{"TRIPLE_DES_3KEY", null},
				{"TRUSTWORTHY", null},
				{"TRY", null},
				{"TSQL", null},
				{"TYPE", null},
				{"TYPE_DESC", null},
				{"TYPE_WARNING", null},
				{"TZOFFSET", null},
				{"UID", null},
				{"UNBOUNDED", null},
				{"UNCOMMITTED", null},
				{"UNIQUEIDENTIFIER", null},
				{"UNLIMITED", null},
				{"UNLOAD", null},
				{"UNLOCK", null},
				{"UNSAFE", null},
				{"UPDLOCK", null},
				{"URL", null},
				{"USEPLAN", null},
				{"USEROPTIONS", null},
				{"USE_TYPE_DEFAULT", null},
				{"USING", null},
				{"UTCDATETIME", null},
				{"VALID_XML", null},
				{"VALIDATION", null},
				{"VALUE", null},
				{"VARBINARY", null},
				{"VARCHAR", null},
				{"VERBOSE", null},
				{"VERIFYONLY", null},
				{"VERSION", null},
				{"VIEW_METADATA", null},
				{"VIRTUAL_DEVICE", null},
				{"VISIBLITY", null},
				{"WEBMETHOD", null},
				{"WEEKDAY", null},
				{"WEIGHT", null},
				{"WELL_FORMED_XML", null},
				{"WIDECHAR", null},
				{"WIDECHAR_ANSI", null},
				{"WIDENATIVE", null},
				{"WINDOWS", null},
				{"WITHIN", null},
				{"WITNESS", null},
				{"WITHOUT", null},
				{"WITHOUT_ARRAY_WRAPPER", null},
				{"WORKLOAD", null},
				{"WSDL", null},
				{"XACT_ABORT", null},
				{"XLOCK", null},
				{"XML", null},
				{"XMLSCHEMA", null},
				{"XQUERY", null},
				{"XSINIL", null},
				{"ZONE", null}
			};

		#endregion

		public string GetHtml(string sqlText)
		{
			string html = "";

			foreach (TSQLToken token in new TSQLTokenizer(sqlText)
			{
				IncludeWhitespace = true
			})
			{
				string escapedText = GetHtmlEscapedText(token.Text);

				string formattedText = GetFormattedText(escapedText);

				if (token.Type != TSQLTokenType.Whitespace)
				{
					System.Drawing.Color color = GetColorForToken(token);

					html += GetHtmlWithColor(
						formattedText,
						color);
				}
				else
				{
					html += formattedText;
				}
			}

			return
				"<span style=\"font-family:consolas;\">\r\n" +
				html +
				"</span>\r\n";
		}

		public System.Drawing.Color GetColorForToken(
			TSQLToken token)
		{
			if (token.Type == TSQLTokenType.Keyword)
			{
				if (token.AsKeyword.Keyword.In(
					TSQLKeywords.NULL,
					TSQLKeywords.AND,
					TSQLKeywords.OR,
					TSQLKeywords.NOT,
					TSQLKeywords.LEFT,
					TSQLKeywords.RIGHT,
					TSQLKeywords.INNER,
					TSQLKeywords.OUTER,
					TSQLKeywords.JOIN,
					TSQLKeywords.ALL,
					TSQLKeywords.ANY,
					TSQLKeywords.SOME,
					TSQLKeywords.BETWEEN,
					TSQLKeywords.CROSS,
					TSQLKeywords.EXISTS,
					TSQLKeywords.IN,
					TSQLKeywords.IS,
					TSQLKeywords.LIKE,
					TSQLKeywords.PIVOT,
					TSQLKeywords.UNPIVOT
					))
				{
					return System.Drawing.Color.Gray;
				}

				if (token.AsKeyword.Keyword.In(
					TSQLKeywords.UPDATE,
					TSQLKeywords.COLLATE
					))
				{
					return System.Drawing.Color.Fuchsia;
				}

				return System.Drawing.Color.Blue;
			}

			if (
				token.Type == TSQLTokenType.Character ||
				token.Type == TSQLTokenType.Operator)
			{
				return System.Drawing.Color.Gray;
			}

			if (
				token.Type == TSQLTokenType.SingleLineComment ||
				token.Type == TSQLTokenType.MultilineComment)
			{
				return System.Drawing.Color.Green;
			}

			if (token.Type == TSQLTokenType.StringLiteral)
			{
				return System.Drawing.Color.Red;
			}

			if (token.Type == TSQLTokenType.SystemIdentifier ||
				token.Type == TSQLTokenType.SystemVariable)
			{
				return System.Drawing.Color.Fuchsia;
			}

			// https://docs.microsoft.com/en-us/sql/t-sql/functions/functions
			if (token.Type == TSQLTokenType.Identifier &&
				!token.Text.StartsWith("[") &&
				KnownFunctions.ContainsKey(token.AsIdentifier.Name.ToUpper()))
			{
				return System.Drawing.Color.Fuchsia;
			}

			if (token.Type == TSQLTokenType.Identifier &&
				!token.Text.StartsWith("[") &&
				PseudoKeywords.ContainsKey(token.AsIdentifier.Name.ToUpper()))
			{
				return System.Drawing.Color.Blue;
			}

			return System.Drawing.Color.Black;
		}

		private static string GetHtmlEscapedText(
			string tokenText)
		{
			return HttpUtility.HtmlEncode(tokenText);
		}

		private static string GetFormattedText(
			string htmlText)
		{
			return htmlText
				.Replace("\r\n", "<br/>")
				.Replace("\r", "<br/>")
				.Replace("\n", "<br/>")
				.Replace("<br/>", "<br/>\r\n")
				.Replace("\t", "&emsp;")
				.Replace(" ", "&nbsp;");
		}

		private static string GetHtmlWithColor(
			string html,
			System.Drawing.Color color)
		{

			return
				"<span style=\"color: " +
				color.Name +
				";\">" +
				html +
				"</span>";
		}
	}
}
